name: retrain-predict
on:
  schedule: [ { cron: '0 3 * * *' } ]
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: pip install pandas scikit-learn sqlite-utils joblib
      - run: python ml/train_predict.py
      - run: git add prices.db && (git diff --cached --quiet || git -c user.email=bot@gh -c user.name=actions commit -m 'ML predict') 
      - run: git push
