name: Price Alert

on:
  schedule:
    # UTC! каждый час
    - cron: "0 * * * *"
  workflow_dispatch:      # кнопка “Run workflow” в UI

env:
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install -r scraper/requirements.txt
      - run: python tools/check_alerts.py
