name: price-alert
on:
  schedule:
    - cron: '*/15 * * * *'          # every 15 min
  workflow_dispatch:

env:
  TG_TOKEN: ${{ }} # Bot token
  TG_CHAT:  ${{ }}  # Chat-ID 

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.12' }

      - name: Install deps
        run: pip install requests sqlite-utils python-telegram-bot==13.15

      - name: Send alerts
        run: python tools/check_alerts.py
